name: Build client to classes.js

on:
  workflow_dispatch:
    inputs:
      relname:
        description: "Release Title"
        default: "Development Build"
        required: true

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      # ...
      - name: "Build To classes.js & Release"
        run: |
          ls
          gradle teavm
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "${{ github.event.inputs.relname }}"
          files: |
            javascript/classes.js
            javascript/classes.js.map
            javascript/assets.epk
